services:
  image_processor:
    image: image
    build: 
      context: image
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 5002
    container_name: image
    restart: always
    ports:
      - "5002:5002"
    volumes: 
      - ./image:/app

  database:
    image: mysql:8.0.34
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - service_network
  
  auth: 
    image: auth
    build: 
      context: auth
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 5001
    container_name: auth
    restart: always
    ports:
      - "5001:5001"
    volumes: 
      - ./auth_service:/app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - service_network

networks:
  service_network:
    driver: bridge