version: "3.8"

services:
  backend:
    build: ./backend/
    ports:
      - "8010:8010"
    container_name: backend
    volumes:
      - ./logs:/app/logs

  filebeat:
    build: ./filebeat/
    container_name: filebeat
    volumes:
      - ./logs:/src/logs
    depends_on:
      - backend
      - elasticsearch
      - kibana
    network_mode: "host"

  elasticsearch:
    build: ./elasticsearch/
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build: ./kibana/
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  events_service:
    build: ./events_service/
    ports:
      - "5000:5000"
    container_name: events_service
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - events_service

volumes:
  elasticsearch_data:
    driver: local
